import type { Metadata } from "next";
import { Geist, Geist_Mono,Roboto } from "next/font/google";
import "@workspace/ui/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFont= Roboto({
  subsets:['latin'],
  style:"normal",
  weight:["100","300","400","500","700","900"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
