import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@workspace/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFont = Roboto({
  subsets: ["latin"],
  style: "normal",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${robotoFont.className}`} lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
